# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '.env'
    TargetFolder: '$(agent.builddirectory)/api'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise (0707557e-135b-4714-b0af-80210ac7bc4e)'
    azureContainerRegistry: '{"loginServer":"openmasjid.azurecr.io", "id" : "/subscriptions/0707557e-135b-4714-b0af-80210ac7bc4e/resourceGroups/open-masjid/providers/Microsoft.ContainerRegistry/registries/openmasjid"}'
    dockerComposeFile: '**/docker-compose.yaml'
    dockerComposeFileArgs: |
      POSTGRES_USER=username
      POSTGRES_PASSWORD=password
      POSTGRES_DB=open_masjid
    action: 'Push services'
    arguments: '--env-file /dev/null'