version: "3.9"
services:
  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/db-data/:/var/lib/postgresql/data/
    env_file:
      - "api/.env"
